const menu = [
  {
    id: 1,
    title: "buttermilk pancakes",
    category: "breakfast",
    price: 40.000,
    img: "./images/item-1.jpeg",
    desc: `Pancake dengan bahan terbaik dipadukan oleh susu dan mentega pilihan serta dilumuri saus stroberi madu serta soft creamcheese `,
  },
  {
    id: 2,
    title: "Burger Platter",
    category: "lunch",
    price: 73.000,
    img: "./images/item-2.jpeg",
    desc: `Burger Beef dengan kentang terbaik, beef dipilih menggunakan daging wagyu `,
  },
  {
    id: 3,
    title: "Strawberry milkshake",
    category: "shakes",
    price: 36,
    img: "./images/item-3.jpeg",
    desc: `Pancake dengan bahan terbaik dipadukan oleh susu dan mentega pilihan serta dilumuri saus stroberi madu serta soft creamcheese`,
  },
  {
    id: 4,
    title: "Mie Telor",
    category: "breakfast",
    price: 30,
    img: "./images/item-4.jpeg",
    desc: `Pancake dengan bahan terbaik dipadukan oleh susu dan mentega pilihan serta dilumuri saus stroberi madu serta soft creamcheese `,
  },
  {
    id: 5,
    title: "Burger Super",
    category: "lunch",
    price: 20,
    img: "./images/item-5.jpeg",
    desc: `Milshake stroberi dengan soct cream cheese di dalamnya `,
  },
  {
    id: 6,
    title: "Oreo Milkshake",
    category: "shakes",
    price: 18,
    img: "./images/item-6.jpeg",
    desc: `Pancake dengan bahan terbaik dipadukan oleh susu dan mentega pilihan serta dilumuri saus stroberi madu serta soft creamcheese`,
  },
  {
    id: 7,
    title: "Bacon Platter",
    category: "breakfast",
    price: 18,
    img: "./images/item-7.jpeg",
    desc: `Pancake dengan bahan terbaik dipadukan oleh susu dan mentega pilihan serta dilumuri saus stroberi madu serta soft creamcheese`,
  },
  {
    id: 8,
    title: "American Burger",
    category: "lunch",
    price: 40,
    img: "./images/item-8.jpeg",
    desc: `Pancake dengan bahan terbaik dipadukan oleh susu dan mentega pilihan serta dilumuri saus stroberi madu serta soft creamcheese`,
  },
];
export default menu;
